# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2d72a61faaedf2e75872b80a60c0ea8f7d69ad777b558ecb200dcf07b1481e3b9d51b83d2a7bafb5cd49246148177abc529c4011b0049d049e3392031957c79

test:
  secret_key_base: f142b994423014152b533d480acce5b76443f68fc3cbd73f9f9380e70e0acca76bf37be60f7684d4bf7a598ef5b7cc29fb8f4ca472b99b274ccc43b48098f909

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
